feat: Add user authentication
COSC481W-2023Fall/Bookworm pull request #22
Opened 2023-10-19 18:07 UTC by huan3846

Introduce user sign-in with authentication tokens
Create user sign-out feature
Implement user sign-in and sign-out functionality

2023-10-19 18:39 UTC, tfurey96 requested changes

2023-10-19 18:39 UTC, tfurey96 commented on frontend/src/components/Navbar.tsx
> +  // If not signed in, it displays "Sign In" and a "Sign Out" button.
```suggestion
  // If not signed in, it displays "Sign In" and a "Sign Up" button.
```

2023-10-19 21:13 UTC, CheesyGamer77 requested changes
A couple minor issues, but otherwise great job!

Once these issues are addressed, we can merge this. It will still say PR/lint failed, but we can fix that separately later.

2023-10-19 21:13 UTC, CheesyGamer77 commented on frontend/src/services/index.ts
> +}
Please add documentation comments for your functions. This makes it easier for others in the team to use your code and understand what it does. An example can be found [in `backend/src/models/book.ts`](https://github.com/COSC481W-2023Fall/Bookworm/blob/main/backend/src/models/book.ts#L33-L41).

2023-10-19 23:38 UTC, tfurey96 reviewed
looks good

2023-10-19 23:40 UTC, tfurey96 approved these changes

2023-10-20 00:46 UTC, huan3846 commented on frontend/src/components/Navbar.tsx
> +          // onSearch={onSearch}
No. Maybe I commented it by mistake

2023-10-20 00:54 UTC, tfurey96 approved these changes
Looks good.

2023-10-20 01:15 UTC, CheesyGamer77 approved these changes

2023-10-20 01:15 UTC, merged